<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="FlowConsole.Tests.Unit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlowConsole.Shared\FlowConsole.Shared.csproj" />
  </ItemGroup>

</Project>
