namespace FlowConsole.Schema.SnapshotValidation;

/// <summary>
/// All stable diagnostic codes for ModelSnapshot v1.
/// Organized by validation phase per diagnostics.md contract.
/// Single source of truth — drift test ensures parity with diagnostics.md.
/// </summary>
public static class SnapshotDiagnosticCodes
{

    public const string SNAPSHOT_SCHEMA_MISSING_REQUIRED_FIELD = "SNAPSHOT_SCHEMA_MISSING_REQUIRED_FIELD";
    public const string SNAPSHOT_SCHEMA_INVALID_TYPE = "SNAPSHOT_SCHEMA_INVALID_TYPE";
    public const string SNAPSHOT_SCHEMA_UNKNOWN_FIELD = "SNAPSHOT_SCHEMA_UNKNOWN_FIELD";
    public const string SNAPSHOT_SCHEMA_INVALID_ENUM_VALUE = "SNAPSHOT_SCHEMA_INVALID_ENUM_VALUE";
    public const string SNAPSHOT_SCHEMA_KIND_DISCRIMINATOR_INVALID = "SNAPSHOT_SCHEMA_KIND_DISCRIMINATOR_INVALID";
    public const string SNAPSHOT_SCHEMA_KIND_PROPERTIES_REQUIRED_MISSING = "SNAPSHOT_SCHEMA_KIND_PROPERTIES_REQUIRED_MISSING";
    public const string SNAPSHOT_SCHEMA_FIELD_MISSING = "SNAPSHOT_SCHEMA_FIELD_MISSING";
    public const string SNAPSHOT_SCHEMA_INVALID_ID_PATTERN = "SNAPSHOT_SCHEMA_INVALID_ID_PATTERN";

    public const string SNAPSHOT_VERSION_MISSING = "SNAPSHOT_VERSION_MISSING";
    public const string SNAPSHOT_VERSION_MAJOR_MISMATCH = "SNAPSHOT_VERSION_MAJOR_MISMATCH";
    public const string SNAPSHOT_VERSION_MINOR_AHEAD = "SNAPSHOT_VERSION_MINOR_AHEAD";

    public const string SNAPSHOT_REF_UNRESOLVED = "SNAPSHOT_REF_UNRESOLVED";
    public const string SNAPSHOT_REF_DUPLICATE_ID = "SNAPSHOT_REF_DUPLICATE_ID";
    public const string SNAPSHOT_REF_DUPLICATE_RELATIONSHIP_ID = "SNAPSHOT_REF_DUPLICATE_RELATIONSHIP_ID";

    public const string SNAPSHOT_LIMIT_BODY_TOO_LARGE = "SNAPSHOT_LIMIT_BODY_TOO_LARGE";
    public const string SNAPSHOT_LIMIT_TOO_MANY_ELEMENTS = "SNAPSHOT_LIMIT_TOO_MANY_ELEMENTS";
    public const string SNAPSHOT_LIMIT_TOO_MANY_RELATIONSHIPS = "SNAPSHOT_LIMIT_TOO_MANY_RELATIONSHIPS";
    public const string SNAPSHOT_LIMIT_RATE_EXCEEDED = "SNAPSHOT_LIMIT_RATE_EXCEEDED";

    public const string SNAPSHOT_FLOW_NOT_ALLOWED_FOR_SOURCE = "SNAPSHOT_FLOW_NOT_ALLOWED_FOR_SOURCE";
    public const string SNAPSHOT_FLOW_STEP_UNRESOLVED = "SNAPSHOT_FLOW_STEP_UNRESOLVED";
    public const string SNAPSHOT_FLOW_ID_DUPLICATE = "SNAPSHOT_FLOW_ID_DUPLICATE";
    public const string SNAPSHOT_FLOW_RELATIONSHIP_MISSING = "SNAPSHOT_FLOW_RELATIONSHIP_MISSING";
    public const string SNAPSHOT_FLOW_ACTION_STEP_INVALID = "SNAPSHOT_FLOW_ACTION_STEP_INVALID";
}
