<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="4.0.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="10.0.0-preview.5.25277.114" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlowConsole.Shared\FlowConsole.Shared.csproj" />
  </ItemGroup>

</Project>
