namespace FlowConsole.Rules.Core.Diagnostics;

/// <summary>
/// All stable diagnostic codes for rule file v1alpha1.
/// Organized by pipeline phase per diagnostics.md contract.
/// </summary>
public static class DiagnosticCodes
{

    public const string RF_PARSE_YAML_SYNTAX_ERROR = "RF_PARSE_YAML_SYNTAX_ERROR";
    public const string RF_PARSE_INVALID_DOCUMENT_TYPE = "RF_PARSE_INVALID_DOCUMENT_TYPE";
    public const string RF_PARSE_UNSUPPORTED_API_VERSION = "RF_PARSE_UNSUPPORTED_API_VERSION";
    public const string RF_PARSE_UNSUPPORTED_KIND = "RF_PARSE_UNSUPPORTED_KIND";
    public const string RF_PARSE_CANONICAL_CONVERSION_FAILED = "RF_PARSE_CANONICAL_CONVERSION_FAILED";

    public const string RF_SCHEMA_MISSING_REQUIRED_FIELD = "RF_SCHEMA_MISSING_REQUIRED_FIELD";
    public const string RF_SCHEMA_INVALID_ENUM_VALUE = "RF_SCHEMA_INVALID_ENUM_VALUE";
    public const string RF_SCHEMA_TYPE_MISMATCH = "RF_SCHEMA_TYPE_MISMATCH";
    public const string RF_SCHEMA_UNKNOWN_FIELD = "RF_SCHEMA_UNKNOWN_FIELD";
    public const string RF_SCHEMA_EMPTY_ARRAY = "RF_SCHEMA_EMPTY_ARRAY";
    public const string RF_SCHEMA_FAMILY_SHAPE_VIOLATION = "RF_SCHEMA_FAMILY_SHAPE_VIOLATION";

    public const string RF_SEM_DUPLICATE_RULE_ID = "RF_SEM_DUPLICATE_RULE_ID";
    public const string RF_SEM_DIFFITEMS_ON_NON_DIFF_TARGET = "RF_SEM_DIFFITEMS_ON_NON_DIFF_TARGET";
    public const string RF_SEM_CHANGEKINDS_ON_NON_DIFF_TARGET = "RF_SEM_CHANGEKINDS_ON_NON_DIFF_TARGET";
    public const string RF_SEM_SOURCE_FAMILY_ON_MODEL_TARGET = "RF_SEM_SOURCE_FAMILY_ON_MODEL_TARGET";
    public const string RF_SEM_FLOW_ENDPOINT_INVALID_ENTITY = "RF_SEM_FLOW_ENDPOINT_INVALID_ENTITY";
    public const string RF_SEM_FLOW_ON_DIFF_TARGET = "RF_SEM_FLOW_ON_DIFF_TARGET";
    public const string RF_SEM_SELECTOR_SHAPE_INCOMPATIBLE = "RF_SEM_SELECTOR_SHAPE_INCOMPATIBLE";
    public const string RF_SEM_LET_SELF_REFERENCE = "RF_SEM_LET_SELF_REFERENCE";

    public const string RF_EXPR_COMPILE_ERROR = "RF_EXPR_COMPILE_ERROR";
    public const string RF_EXPR_UNKNOWN_BINDING = "RF_EXPR_UNKNOWN_BINDING";
    public const string RF_EXPR_UNKNOWN_HELPER = "RF_EXPR_UNKNOWN_HELPER";
    public const string RF_EXPR_UNSUPPORTED_CONSTRUCT = "RF_EXPR_UNSUPPORTED_CONSTRUCT";
    public const string RF_EXPR_NON_BOOLEAN_ASSERT = "RF_EXPR_NON_BOOLEAN_ASSERT";
    public const string RF_EXPR_SIGNATURE_MISMATCH = "RF_EXPR_SIGNATURE_MISMATCH";
    public const string RF_EXPR_TYPE_MISMATCH = "RF_EXPR_TYPE_MISMATCH";
    public const string RF_EXPR_HETEROGENEOUS_COLLECTION = "RF_EXPR_HETEROGENEOUS_COLLECTION";
    public const string RF_EXPR_REGEX_UNSUPPORTED_FEATURE = "RF_EXPR_REGEX_UNSUPPORTED_FEATURE";
    public const string RF_EXPR_MESSAGE_UNKNOWN_BINDING = "RF_EXPR_MESSAGE_UNKNOWN_BINDING";
    public const string RF_EXPR_SHADOWED_BINDING = "RF_EXPR_SHADOWED_BINDING";
    public const string RF_EXPR_RESERVED_NAME = "RF_EXPR_RESERVED_NAME";
    public const string RF_EXPR_LET_DEPENDENCY_CYCLE = "RF_EXPR_LET_DEPENDENCY_CYCLE";

    public const string RF_NORM_CANONICAL_KEY_CONFLICT = "RF_NORM_CANONICAL_KEY_CONFLICT";
    public const string RF_NORM_DEFAULTS_CONFLICT = "RF_NORM_DEFAULTS_CONFLICT";
    public const string RF_NORM_ASSEMBLY_FAILED = "RF_NORM_ASSEMBLY_FAILED";

    public const string RE_SUBJECT_TOO_LARGE = "RE_SUBJECT_TOO_LARGE";
    public const string RE_EXPRESSION_BUDGET_EXCEEDED = "RE_EXPRESSION_BUDGET_EXCEEDED";
    public const string RE_EXPRESSION_TIMEOUT = "RE_EXPRESSION_TIMEOUT";
    public const string RE_EXPRESSION_NULL_ORDER = "RE_EXPRESSION_NULL_ORDER";
    public const string RE_EXPRESSION_NULL_ARITHMETIC = "RE_EXPRESSION_NULL_ARITHMETIC";
    public const string RE_PATH_ENDPOINTS_EMPTY = "RE_PATH_ENDPOINTS_EMPTY";
    public const string RE_DIFF_SNAPSHOT_MISSING = "RE_DIFF_SNAPSHOT_MISSING";
    public const string RE_EXPRESSION_RUNTIME_ERROR = "RE_EXPRESSION_RUNTIME_ERROR";
    public const string RE_PATH_TOO_MANY_RESULTS = "RE_PATH_TOO_MANY_RESULTS";
}
